apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: repairman-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: maintenancelimits.repairman.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.limit
    format: int32
    name: Percent
    type: integer
  - JSONPath: .status.limit
    format: int32
    name: Count
    type: integer
  group: repairman.k8s.io
  names:
    kind: MaintenanceLimit
    plural: maintenancelimits
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MaintenanceLimit is the Schema for the maintenancelimits API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MaintenanceLimitSpec defines the desired state of MaintenanceLimit
          properties:
            limit:
              maximum: 100
              minimum: 0
              type: integer
            policies:
              items:
                description: MaintenancePolicy ...
                type: string
              type: array
          type: object
        status:
          description: MaintenanceLimitStatus defines the observed state of MaintenanceLimit
          properties:
            limit:
              description: Limit dynamically updated by operator based on current
                cluster state
              type: integer
            unavailable:
              additionalProperties:
                description: MaintenancePolicy ...
                type: string
              description: Unavailable nodes filtered by above policies
              type: object
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: maintenancerequests.repairman.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.name
    format: byte
    name: Name
    type: string
  - JSONPath: .spec.type
    format: byte
    name: Type
    type: string
  - JSONPath: .spec.state
    format: byte
    name: State
    type: string
  group: repairman.k8s.io
  names:
    kind: MaintenanceRequest
    plural: maintenancerequests
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MaintenanceRequest is the Schema for the maintenancerequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MaintenanceRequestSpec defines the desired state of MaintenanceRequest
          properties:
            name:
              type: string
            state:
              description: MaintenanceState defined below
              enum:
              - Pending
              - Approved
              - InProgress
              - Completed
              type: string
            type:
              enum:
              - node
              type: string
          type: object
        status:
          description: MaintenanceRequestStatus defines the observed state of MaintenanceRequest
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: maintenanceselectors.repairman.k8s.io
spec:
  group: repairman.k8s.io
  names:
    kind: MaintenanceSelector
    plural: maintenanceselectors
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MaintenanceSelector is the Schema for the maintenanceselectors
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MaintenanceSelectorSpec defines the desired state of MaintenanceSelector
          type: object
        status:
          description: MaintenanceSelectorStatus defines the observed state of MaintenanceSelector
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: repairman-leader-election-role
  namespace: repairman-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: repairman-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenancelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenancelimits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenancerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenancerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenanceselectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repairman.k8s.io
  resources:
  - maintenanceselectors/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repairman-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: repairman-leader-election-rolebinding
  namespace: repairman-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: repairman-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: repairman-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: repairman-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: repairman-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: repairman-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: repairman-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: repairman-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: repairman-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager
  name: repairman-controller-manager-metrics-service
  namespace: repairman-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: repairman-controller-manager
  namespace: repairman-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        image: quay.io/awesomenix/repairman-manager:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
