
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: maintenancerequests.repairman.k8s.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.name
    format: byte
    name: Name
    type: string
  - JSONPath: .spec.type
    format: byte
    name: Type
    type: string
  - JSONPath: .spec.state
    format: byte
    name: State
    type: string
  group: repairman.k8s.io
  names:
    kind: MaintenanceRequest
    plural: maintenancerequests
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MaintenanceRequest is the Schema for the maintenancerequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MaintenanceRequestSpec defines the desired state of MaintenanceRequest
          properties:
            name:
              type: string
            state:
              description: MaintenanceState defined below
              enum:
              - Pending
              - Approved
              - InProgress
              - Completed
              type: string
            type:
              enum:
              - node
              type: string
          type: object
        status:
          description: MaintenanceRequestStatus defines the observed state of MaintenanceRequest
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
